// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0TLu0xmIeJOoBlj5hrv4LPolCAlv0AvE',
    appId: '1:889421438292:web:e9176af3f68351b8fa3cc1',
    messagingSenderId: '889421438292',
    projectId: 'travel-app-c02d6',
    authDomain: 'travel-app-c02d6.firebaseapp.com',
    storageBucket: 'travel-app-c02d6.appspot.com',
    measurementId: 'G-F20S6VS3GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhyCnak3KCxB50e8fBulHm7v7VTJEfuhg',
    appId: '1:889421438292:android:9a6ab8111da00649fa3cc1',
    messagingSenderId: '889421438292',
    projectId: 'travel-app-c02d6',
    storageBucket: 'travel-app-c02d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQk94etE2PeQ_1oJcjtdFWEL7dRFIdxHw',
    appId: '1:889421438292:ios:002e76b7b22392b1fa3cc1',
    messagingSenderId: '889421438292',
    projectId: 'travel-app-c02d6',
    storageBucket: 'travel-app-c02d6.appspot.com',
    iosBundleId: 'com.dnlsdn.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQk94etE2PeQ_1oJcjtdFWEL7dRFIdxHw',
    appId: '1:889421438292:ios:0f68320f84667e39fa3cc1',
    messagingSenderId: '889421438292',
    projectId: 'travel-app-c02d6',
    storageBucket: 'travel-app-c02d6.appspot.com',
    iosBundleId: 'com.dnlsdn.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0TLu0xmIeJOoBlj5hrv4LPolCAlv0AvE',
    appId: '1:889421438292:web:62298c2cae8b0908fa3cc1',
    messagingSenderId: '889421438292',
    projectId: 'travel-app-c02d6',
    authDomain: 'travel-app-c02d6.firebaseapp.com',
    storageBucket: 'travel-app-c02d6.appspot.com',
    measurementId: 'G-BCF0LXBHBX',
  );
}
